### ISSUE TITLE
Where is `fromDIMACS` ?

### ISSUE THREAD

**Issue by tobynet** [ledyba/Programming_on_SAT#1]
chapter3 [「論理式を扱うHaskellライブラリを使う」](https://github.com/ledyba/Programming_on_SAT/blob/5ecea4bc95468eadf2b27e982c01e4ece480e477/chapter3.md)  にて、 `fromDIMACS` が 使われています。 しかし、 `Sally` には  `fromDIMACS` が含まれていないように見えます。

機能的には bf2sat の [RCNF.hs](https://github.com/ledyba/bf2sat/blob/5ffdfbdf9b15d7d01bf00a6b475b8fccdc40b5d3/lib/Brainfuck2Sat/RCNF.hs#L17-L29) に含まれる `fromDIMACS` が必要なのではありませんでしょうか。

**Comment by ledyba** [comment]
Thank you! That's right.
I will move that function form bf2sat to Sally. Stay tuned.

**Comment by ledyba** [comment]
遅れてすいません。
SallyにfromDIMACSを移植しました。これで動くと思います。

**Comment by tobynet** [comment]
:bow: :sweat_drops:
